######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 2 19:03:41 2010
######################################################################

QT += testlib xml xmlpatterns
TEMPLATE = app
CONFIG -= app_bundle

MOC_DIR = ./tmp
OBJECTS_DIR = ./tmp
UI_DIR = ./tmp

TARGET =
DEPENDPATH += .
INCLUDEPATH += . \
               ../KExperiment \
               ../3rd
               
unix:LIBS+= ../KExperiment/tmp/ComponentList.o \
       ../KExperiment/tmp/Action.o \
       ../KExperiment/tmp/OutputComponent.o

macx:LIBS +=  $(OBJECT_FILE_DIR_normal)/ComponentList.o \
              $(OBJECT_FILE_DIR_normal)/Action.o \
              $(OBJECT_FILE_DIR_normal)/OutputComponent.o 
# Input
HEADERS += ComponentListTest.h \
           ../KExperiment/Components/ComponentList.h \
           ../KExperiment/Components/Actions/Action.h \
           ../KExperiment/Components/OutputComponent.h
           
SOURCES += ComponentListTest.cpp
